<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>panda_mjk_hardware</name>
  <version>0.0.0</version>
  <description>Custom hardware interface plugin for MuJoCo to support Franka controllers.</description>
  <maintainer email="harindu@example.com">harindu</maintainer>
  <license>Apache-2.0</license>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <depend>rclcpp</depend>
  <depend>hardware_interface</depend>
  <depend>mujoco_ros2_control</depend>
  <depend>pluginlib</depend>
  <depend>franka_semantic_components</depend>
  <depend>franka_hardware</depend>

  <test_depend>ament_lint_auto</test_depend>
  <test_depend>ament_lint_common</test_depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
