<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>panda_mjk</name>
  <version>0.0.0</version>
  <description>Unified ROS 2 package for Franka Emika Panda sim and real control with Cartesian teleop.</description>
  <maintainer email="harindu@example.com">harindu</maintainer>
  <license>Apache-2.0</license>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <depend>rclcpp</depend>
  <depend>geometry_msgs</depend>
  <depend>sensor_msgs</depend>
  <depend>std_srvs</depend>
  <depend>controller_manager</depend>
  <depend>ros2_control</depend>
  <depend>ros2_controllers</depend>
  <depend>mujoco_ros2_control</depend>
  <depend>franka_hardware</depend>
  <depend>franka_description</depend>
  <depend>joy</depend>
  <depend>moveit_servo</depend>
  <depend>xacro</depend>
  <depend>control_msgs</depend>
  <depend>rclcpp_action</depend>
  <depend>interactive_markers</depend>
  <depend>visualization_msgs</depend>
  <depend>tf2</depend>
  <depend>tf2_ros</depend>
  <depend>tf2_geometry_msgs</depend>

  <test_depend>ament_lint_auto</test_depend>
  <test_depend>ament_lint_common</test_depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
